# -*- coding: utf-8 -*-
"""main_model_mscma_net_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uXGPSuxENWQZMy0Q5kUfeFBBVmjHc56U
"""

# Colab already ships with torch + CUDA. We only need a few extra light packages.
# NOTE: We do NOT depend on the mamba-ssm CUDA package (it's finicky to install on Colab).
# Instead we implement the selective-scan (S6) Mamba block in pure PyTorch below — fully "from scratch".
!pip install -q wfdb scikit-learn tqdm

import os, ast, math, json, time, random
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score, f1_score, classification_report, multilabel_confusion_matrix
import matplotlib.pyplot as plt
from tqdm.auto import tqdm

SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED); torch.cuda.manual_seed_all(SEED)

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Device:', DEVICE)

from google.colab import drive
drive.mount('/content/drive')

# ---- EDIT THESE TWO PATHS IF NEEDED ----
ZIP_PATH   = '/content/drive/MyDrive/ptb-xl.zip'          # location of your uploaded zip
EXTRACT_TO = '/content/ptbxl_data'                        # where to unzip inside the Colab VM (fast local disk)
CACHE_DIR  = '/content/drive/MyDrive/ptbxl_cache'          # preprocessed .npy cache + checkpoints saved back to Drive
# -----------------------------------------

os.makedirs(EXTRACT_TO, exist_ok=True)
os.makedirs(CACHE_DIR, exist_ok=True)

if not os.path.exists(os.path.join(EXTRACT_TO, 'ptbxl_database.csv')):
    print('Unzipping... this can take a few minutes the first time.')
    import zipfile
    with zipfile.ZipFile(ZIP_PATH, 'r') as zf:
        zf.extractall(EXTRACT_TO)
    print('Done unzipping.')
else:
    print('Already extracted, skipping unzip.')

# The PTB-XL zip usually extracts into a single top-level folder
# (e.g. 'ptb-xl-a-large-publicly-available-electrocardiography-dataset-1.0.3/').
# Auto-detect it so the rest of the notebook doesn't break if the folder name differs.
def find_ptbxl_root(base):
    for root, dirs, files in os.walk(base):
        if 'ptbxl_database.csv' in files:
            return root + '/'
    raise FileNotFoundError('Could not locate ptbxl_database.csv inside the extracted zip. '
                             'Check that ptb-xl.zip is the official PTB-XL release.')

PTBXL_ROOT = find_ptbxl_root(EXTRACT_TO)
print('PTB-XL root:', PTBXL_ROOT)

SAMPLING_RATE = 100     # 100 Hz (10s records -> 1000 timesteps). Use 500 for the high-res variant (slower).
CLASSES = ['NORM', 'MI', 'STTC', 'CD', 'HYP']
N_CLASSES = len(CLASSES)

# ---- load metadata ----
Y = pd.read_csv(PTBXL_ROOT + 'ptbxl_database.csv', index_col='ecg_id')
Y.scp_codes = Y.scp_codes.apply(ast.literal_eval)

agg_df = pd.read_csv(PTBXL_ROOT + 'scp_statements.csv', index_col=0)
agg_df = agg_df[agg_df.diagnostic == 1]

def aggregate_diagnostic(scp_dict):
    labels = set()
    for code_ in scp_dict.keys():
        if code_ in agg_df.index:
            labels.add(agg_df.loc[code_].diagnostic_class)
    return list(labels)

Y['diagnostic_superclass'] = Y.scp_codes.apply(aggregate_diagnostic)

# keep only records that have at least one of our 5 target superclasses
Y = Y[Y.diagnostic_superclass.apply(lambda l: len(set(l) & set(CLASSES)) > 0)].copy()

# multi-hot label matrix
label_matrix = np.zeros((len(Y), N_CLASSES), dtype=np.float32)
for i, labels in enumerate(Y.diagnostic_superclass):
    for c in labels:
        if c in CLASSES:
            label_matrix[i, CLASSES.index(c)] = 1.0

print('Total usable records:', len(Y))
print('Per-class positive counts:')
for i, c in enumerate(CLASSES):
    print(f'  {c}: {int(label_matrix[:, i].sum())}')

X_CACHE = os.path.join(CACHE_DIR, f'X_{SAMPLING_RATE}hz.npy')
Y_CACHE = os.path.join(CACHE_DIR, f'Y_labels.npy')
IDX_CACHE = os.path.join(CACHE_DIR, f'ecg_ids.npy')

def load_raw_signals(df, sampling_rate, root):
    import wfdb
    fnames = df.filename_lr if sampling_rate == 100 else df.filename_hr
    signals = []
    for f in tqdm(fnames, desc='Loading waveforms'):
        sig, meta = wfdb.rdsamp(root + f)
        signals.append(sig.astype(np.float32))
    return np.stack(signals, axis=0)  # (N, T, 12)

if os.path.exists(X_CACHE) and os.path.exists(Y_CACHE):
    print('Loading cached arrays from Drive...')
    X = np.load(X_CACHE)
    label_matrix = np.load(Y_CACHE)
    ecg_ids = np.load(IDX_CACHE)
else:
    X = load_raw_signals(Y, SAMPLING_RATE, PTBXL_ROOT)   # (N, T, 12)
    ecg_ids = Y.index.values
    np.save(X_CACHE, X)
    np.save(Y_CACHE, label_matrix)
    np.save(IDX_CACHE, ecg_ids)
    print('Cached to', CACHE_DIR)

strat_folds = Y.strat_fold.values
print('X shape:', X.shape, '| labels shape:', label_matrix.shape)

!pip install -q wfdb
import wfdb
print(wfdb.__version__)

train_mask = strat_folds <= 8
val_mask   = strat_folds == 9
test_mask  = strat_folds == 10

X_train, y_train = X[train_mask], label_matrix[train_mask]
X_val,   y_val   = X[val_mask],   label_matrix[val_mask]
X_test,  y_test  = X[test_mask],  label_matrix[test_mask]

print('Train:', X_train.shape, ' Val:', X_val.shape, ' Test:', X_test.shape)

# per-lead standardization computed on TRAIN ONLY, applied to all splits
n_leads = X_train.shape[-1]
lead_mean = X_train.reshape(-1, n_leads).mean(axis=0)
lead_std  = X_train.reshape(-1, n_leads).std(axis=0) + 1e-8

def normalize(x):
    return (x - lead_mean) / lead_std

X_train = normalize(X_train)
X_val   = normalize(X_val)
X_test  = normalize(X_test)

"""## Change 1 — Train-time data augmentation
Adds jitter, per-lead amplitude scaling, small time shift, and occasional single-lead dropout **only to the training split**. This is standard regularization for small-to-mid sized ECG datasets and should reduce overfitting (your original run showed train_loss dropping to 0.22 while val_loss rose back to 0.71-0.94 — a classic overfitting signature).
"""

class PTBXLDataset(Dataset):
    """
    Same as before, but the TRAIN split now gets light, physiologically
    plausible augmentation applied on-the-fly (val/test stay untouched
    so evaluation numbers remain a fair, deterministic readout).

    Why these four and not others: they mimic real acquisition variance
    (electrode noise, gain differences, patient positioning / R-peak
    phase, occasional bad lead) without destroying the diagnostic
    morphology of the ECG (we do NOT time-reverse or lead-shuffle).
    """
    def __init__(self, X, y, train=False, aug_prob=0.5):
        # X: (N, T, 12) -> we store as (N, 12, T) for Conv1d
        self.X = torch.from_numpy(X).float().permute(0, 2, 1).contiguous()
        self.y = torch.from_numpy(y).float()
        self.train = train
        self.aug_prob = aug_prob

    def __len__(self):
        return len(self.X)

    def _augment(self, x):
        # x: (12, T)
        if random.random() < self.aug_prob:
            # additive Gaussian noise -> simulates muscle/mains noise
            x = x + torch.randn_like(x) * random.uniform(0.0, 0.05)
        if random.random() < self.aug_prob:
            # per-lead amplitude scaling -> simulates electrode/gain variance
            scale = 1.0 + (torch.rand(x.shape[0], 1) - 0.5) * 0.2   # +/-10%
            x = x * scale
        if random.random() < self.aug_prob:
            # small circular time shift -> simulates R-peak phase variability
            shift = random.randint(-50, 50)
            x = torch.roll(x, shifts=shift, dims=-1)
        if random.random() < 0.2:
            # random single-lead dropout -> simulates a noisy/disconnected lead
            x = x.clone()
            lead = random.randint(0, x.shape[0] - 1)
            x[lead] = 0.0
        return x

    def __getitem__(self, idx):
        x = self.X[idx]
        if self.train:
            x = self._augment(x)
        return x, self.y[idx]

BATCH_SIZE = 64

train_ds = PTBXLDataset(X_train, y_train, train=True,  aug_prob=0.5)
val_ds   = PTBXLDataset(X_val,   y_val,   train=False)
test_ds  = PTBXLDataset(X_test,  y_test,  train=False)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=0, drop_last=True)
val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, num_workers=0)
test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

print('Batches -> train:', len(train_loader), ' val:', len(val_loader), ' test:', len(test_loader))

"""## Change 2 — Squeeze-and-Excitation + extra dropout in the backbone
- `SEBlock` added inside every `MultiScaleConvBlock` so the network can learn to reweight which multi-kernel branch matters per-sample (adds <1% extra parameters).
- Added `Dropout` after each pooling stage and inside the Mamba block's output projection. With ~2.5M parameters on ~17k training records, the original model had very little explicit regularization outside the classifier head — this was very likely a big driver of the overfitting seen in your training curve.
"""

class SEBlock(nn.Module):
    """Squeeze-and-Excitation channel attention. Cheap (few thousand params)
    way to let the network reweight lead/scale channels instead of treating
    all Conv branches equally."""
    def __init__(self, channels, reduction=8):
        super().__init__()
        self.avg_pool = nn.AdaptiveAvgPool1d(1)
        hidden = max(channels // reduction, 4)
        self.fc = nn.Sequential(
            nn.Linear(channels, hidden), nn.GELU(),
            nn.Linear(hidden, channels), nn.Sigmoid(),
        )

    def forward(self, x):  # x: (B, C, T)
        w = self.avg_pool(x).squeeze(-1)
        w = self.fc(w).unsqueeze(-1)
        return x * w


class MultiScaleConvBlock(nn.Module):
    """Parallel multi-kernel-size Conv1d branches, concatenated, projected,
    SE-reweighted, residual."""
    def __init__(self, in_ch, out_ch, kernel_sizes=(3, 7, 15, 31)):
        super().__init__()
        assert out_ch % len(kernel_sizes) == 0
        branch_ch = out_ch // len(kernel_sizes)
        self.branches = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(in_ch, branch_ch, k, padding=k // 2),
                nn.BatchNorm1d(branch_ch),
                nn.GELU(),
            ) for k in kernel_sizes
        ])
        self.proj = nn.Conv1d(branch_ch * len(kernel_sizes), out_ch, 1)
        self.bn = nn.BatchNorm1d(out_ch)
        self.se = SEBlock(out_ch)
        self.act = nn.GELU()
        self.residual = nn.Conv1d(in_ch, out_ch, 1) if in_ch != out_ch else nn.Identity()

    def forward(self, x):
        out = torch.cat([b(x) for b in self.branches], dim=1)
        out = self.se(self.bn(self.proj(out)))
        return self.act(out + self.residual(x))


class MambaBlock(nn.Module):
    """Selective State Space (S6) block, pure PyTorch. Pre-norm residual.
    (unchanged core scan logic -- only addition is an output dropout so the
    long-range mixing path can't memorize training-set-specific patterns)."""
    def __init__(self, d_model, d_state=16, d_conv=4, expand=2, dt_rank=None, dropout=0.1):
        super().__init__()
        self.d_model = d_model
        self.d_inner = expand * d_model
        self.d_state = d_state
        self.dt_rank = dt_rank or math.ceil(d_model / 16)

        self.norm = nn.LayerNorm(d_model)
        self.in_proj = nn.Linear(d_model, self.d_inner * 2, bias=False)
        self.conv1d = nn.Conv1d(self.d_inner, self.d_inner, kernel_size=d_conv,
                                 groups=self.d_inner, padding=d_conv - 1, bias=True)
        self.x_proj = nn.Linear(self.d_inner, self.dt_rank + 2 * self.d_state, bias=False)
        self.dt_proj = nn.Linear(self.dt_rank, self.d_inner, bias=True)

        A = torch.arange(1, self.d_state + 1, dtype=torch.float32).repeat(self.d_inner, 1)
        self.A_log = nn.Parameter(torch.log(A))          # (d_inner, d_state)
        self.D = nn.Parameter(torch.ones(self.d_inner))  # (d_inner,)
        self.out_proj = nn.Linear(self.d_inner, d_model, bias=False)
        self.drop = nn.Dropout(dropout)

    def forward(self, x):
        # x: (B, L, d_model)
        residual = x
        x = self.norm(x)
        x_in, z = self.in_proj(x).chunk(2, dim=-1)          # (B,L,d_inner) each

        x_conv = self.conv1d(x_in.transpose(1, 2))[:, :, :x_in.shape[1]]
        x_conv = F.silu(x_conv.transpose(1, 2))              # (B,L,d_inner)

        x_dbl = self.x_proj(x_conv)
        delta, B_ssm, C_ssm = torch.split(
            x_dbl, [self.dt_rank, self.d_state, self.d_state], dim=-1)
        delta = F.softplus(self.dt_proj(delta))               # (B,L,d_inner)

        A = -torch.exp(self.A_log)                            # (d_inner, d_state)
        y = self.selective_scan(x_conv, delta, A, B_ssm, C_ssm, self.D)
        y = y * F.silu(z)
        return residual + self.drop(self.out_proj(y))

    @staticmethod
    def selective_scan(u, delta, A, B, C, D):
        # Numerically-stable PARALLEL SCAN (Blelloch/Hillis-Steele) for the
        # linear recurrence:  state_t = a_t * state_{t-1} + b_t
        # (unchanged from the original -- this part was already correct)
        b, l, d_in = u.shape
        n = A.shape[1]
        a_t = torch.exp(delta.unsqueeze(-1) * A)                              # (b,l,d_in,n), in (0,1)
        b_t = delta.unsqueeze(-1) * B.unsqueeze(2) * u.unsqueeze(-1)          # (b,l,d_in,n)

        A_scan, B_scan = a_t, b_t
        d = 1
        while d < l:
            A_shift = torch.ones_like(A_scan)
            B_shift = torch.zeros_like(B_scan)
            A_shift[:, d:] = A_scan[:, :l - d]
            B_shift[:, d:] = B_scan[:, :l - d]
            B_scan = A_scan * B_shift + B_scan
            A_scan = A_shift * A_scan
            d *= 2

        state = B_scan
        y = torch.einsum('bldn,bln->bld', state, C)
        return y + u * D


class AttentionBlock(nn.Module):
    """Pre-norm multi-head self-attention + FFN, transformer-encoder style."""
    def __init__(self, d_model, num_heads=4, dropout=0.1):
        super().__init__()
        self.norm1 = nn.LayerNorm(d_model)
        self.mha = nn.MultiheadAttention(d_model, num_heads, dropout=dropout, batch_first=True)
        self.norm2 = nn.LayerNorm(d_model)
        self.ff = nn.Sequential(
            nn.Linear(d_model, d_model * 4), nn.GELU(), nn.Dropout(dropout),
            nn.Linear(d_model * 4, d_model),
        )

    def forward(self, x):
        h = self.norm1(x)
        attn_out, attn_w = self.mha(h, h, h, need_weights=False)
        x = x + attn_out
        x = x + self.ff(self.norm2(x))
        return x


class MultiScaleCNNMambaAttnNet(nn.Module):
    def __init__(self, in_channels=12, num_classes=5, base_channels=32,
                 mamba_layers=2, attn_heads=4, dropout=0.3, stage_dropout=0.1):
        super().__init__()
        self.stem = nn.Sequential(
            nn.Conv1d(in_channels, base_channels, 7, padding=3),
            nn.BatchNorm1d(base_channels), nn.GELU(),
        )
        self.stage1 = MultiScaleConvBlock(base_channels, base_channels * 2)
        self.pool1 = nn.MaxPool1d(2)
        self.drop1 = nn.Dropout(stage_dropout)
        self.stage2 = MultiScaleConvBlock(base_channels * 2, base_channels * 4)
        self.pool2 = nn.MaxPool1d(2)
        self.drop2 = nn.Dropout(stage_dropout)
        self.stage3 = MultiScaleConvBlock(base_channels * 4, base_channels * 8)
        self.pool3 = nn.MaxPool1d(2)
        self.drop3 = nn.Dropout(stage_dropout)

        d_model = base_channels * 8
        self.mamba_layers = nn.ModuleList([MambaBlock(d_model, dropout=dropout) for _ in range(mamba_layers)])
        self.attn = AttentionBlock(d_model, num_heads=attn_heads, dropout=dropout)

        self.classifier = nn.Sequential(
            nn.Linear(d_model * 2, d_model),
            nn.GELU(), nn.Dropout(dropout),
            nn.Linear(d_model, num_classes),
        )

    def forward(self, x):                      # x: (B, 12, T)
        x = self.stem(x)
        x = self.drop1(self.pool1(self.stage1(x)))
        x = self.drop2(self.pool2(self.stage2(x)))
        x = self.drop3(self.pool3(self.stage3(x)))   # (B, d_model, T')
        x = x.transpose(1, 2)                   # (B, T', d_model)
        for layer in self.mamba_layers:
            x = layer(x)
        x = self.attn(x)
        x_t = x.transpose(1, 2)
        feat = torch.cat([
            F.adaptive_avg_pool1d(x_t, 1).squeeze(-1),
            F.adaptive_max_pool1d(x_t, 1).squeeze(-1),
        ], dim=-1)
        return self.classifier(feat)            # (B, num_classes) logits


model = MultiScaleCNNMambaAttnNet(in_channels=12, num_classes=N_CLASSES).to(DEVICE)
n_params = sum(p.numel() for p in model.parameters())
print(f'Model parameters: {n_params:,}')

class FocalBCELoss(nn.Module):
    """
    BCEWithLogits + per-class pos_weight (for the NORM/HYP imbalance you already
    had) + a focal modulating term (gamma) that down-weights *easy* examples the
    model already gets right, so gradient signal concentrates on the hard cases
    (this is exactly where HYP -- your weakest class at AUC 0.905 -- needs help).
    A small amount of label smoothing is also applied to soften the hard 0/1
    targets, which tends to reduce over-confident, poorly-calibrated logits.
    """
    def __init__(self, pos_weight, gamma=1.5, label_smoothing=0.02):
        super().__init__()
        self.register_buffer('pos_weight', pos_weight)
        self.gamma = gamma
        self.eps = label_smoothing

    def forward(self, logits, targets):
        targets = targets * (1 - self.eps) + 0.5 * self.eps
        p = torch.sigmoid(logits)
        pt = torch.where(targets >= 0.5, p, 1 - p)
        focal_weight = (1 - pt).clamp(min=1e-4) ** self.gamma
        bce = F.binary_cross_entropy_with_logits(
            logits, targets, pos_weight=self.pos_weight, reduction='none')
        return (focal_weight * bce).mean()


def mixup_batch(x, y, alpha=0.2):
    """
    Mixup adapted for multi-label targets: linearly interpolate both the raw
    signal and the multi-hot label vector between two random training examples.
    Acts as a strong, well-established regularizer -- set MIXUP_ALPHA = 0 below
    to disable it if you want an ablation run without it.
    """
    if alpha <= 0:
        return x, y
    lam = float(np.random.beta(alpha, alpha))
    idx = torch.randperm(x.size(0), device=x.device)
    x_mixed = lam * x + (1 - lam) * x[idx]
    y_mixed = lam * y + (1 - lam) * y[idx]
    return x_mixed, y_mixed

# quick shape sanity check
with torch.no_grad():
    dummy = torch.randn(2, 12, 1000).to(DEVICE)
    out = model(dummy)
    print('Output shape:', out.shape)  # expect (2, 5)

"""## Change 3 — Loss, LR schedule, and Stochastic Weight Averaging (SWA)
- **Loss**: `BCEWithLogitsLoss` -> `FocalBCELoss` (keeps your pos_weight, adds focal term + light label smoothing).
- **LR schedule**: plain cosine -> linear warmup (3 epochs) + cosine decay, which is standard practice for stabilizing early training in deeper/attention-containing models.
- **SWA**: for the last ~15 epochs we average the weights along the training trajectory (`torch.optim.swa_utils`). SWA very reliably improves generalization/AUC on exactly this kind of 'good but noisy val curve' pattern (your val_auc bounced between 0.91-0.93 across epochs instead of climbing smoothly).
"""

pos_counts = y_train.sum(axis=0)
neg_counts = len(y_train) - pos_counts
pos_weight = torch.tensor(neg_counts / np.clip(pos_counts, 1, None), dtype=torch.float32).to(DEVICE)
print('pos_weight per class:', dict(zip(CLASSES, pos_weight.cpu().numpy().round(2))))

criterion = FocalBCELoss(pos_weight=pos_weight, gamma=1.5, label_smoothing=0.02).to(DEVICE)

EPOCHS = 22                # SHORTENED (was 50): your last two runs both showed the model is only
                           # genuinely good for epochs ~13-21 -- val_loss climbs from 0.20 to 0.55+ and
                           # val_macroAUC drifts down from 0.93 to ~0.91 well before epoch 50. Running to
                           # epoch 50 just spent 28 extra epochs training on an increasingly overfit model
                           # and forced SWA to average across that overfit tail, diluting the average.
LR = 1e-3
WEIGHT_DECAY = 2e-4
WARMUP_EPOCHS = 3          # linear warmup, then cosine decay -- smooths early-training instability
MIXUP_ALPHA = 0.2          # set to 0.0 to ablate mixup
SWA_START_EPOCH = 14       # right after the observed plateau (best single epoch was 13 across both
                           # prior runs). With EPOCHS=22, SWA now averages only epochs 14-21 (8 epochs,
                           # all still in the healthy region), instead of 34 epochs that drift into
                           # overfitting. This is a tighter, more classically-correct SWA window.

optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)

def lr_lambda(epoch):
    if epoch < WARMUP_EPOCHS:
        return (epoch + 1) / WARMUP_EPOCHS
    progress = (epoch - WARMUP_EPOCHS) / max(1, (EPOCHS - WARMUP_EPOCHS))
    return 0.5 * (1 + math.cos(math.pi * progress))

scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)
scaler = torch.amp.GradScaler('cuda', enabled=(DEVICE.type == 'cuda'))

swa_model = torch.optim.swa_utils.AveragedModel(model)
swa_scheduler = torch.optim.swa_utils.SWALR(optimizer, swa_lr=LR * 0.1)

EARLY_STOP_PATIENCE = 10
CKPT_PATH = os.path.join(CACHE_DIR, 'best_mscma_net_main.pt')
SWA_CKPT_PATH = os.path.join(CACHE_DIR, 'swa_mscma_net_main.pt')

def run_epoch(loader, train=True, mixup_alpha=0.0):
    model.train(train)
    total_loss = 0.0
    all_logits, all_targets = [], []

    for xb, yb in tqdm(loader, leave=False):
        xb, yb = xb.to(DEVICE, non_blocking=True), yb.to(DEVICE, non_blocking=True)

        if train:
            xb_in, yb_in = mixup_batch(xb, yb, mixup_alpha) if mixup_alpha > 0 else (xb, yb)
            optimizer.zero_grad(set_to_none=True)
            with torch.amp.autocast('cuda', enabled=(DEVICE.type == 'cuda')):
                logits = model(xb_in)
                loss = criterion(logits, yb_in)
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(optimizer)
            scaler.update()
        else:
            with torch.no_grad(), torch.amp.autocast('cuda', enabled=(DEVICE.type == 'cuda')):
                logits = model(xb)
                loss = criterion(logits, yb)

        total_loss += loss.item() * xb.size(0)
        all_logits.append(logits.detach().float().cpu())
        all_targets.append(yb.detach().float().cpu())  # log true targets even under mixup (rough train-time signal only)

    all_logits = torch.cat(all_logits).numpy()
    all_targets = torch.cat(all_targets).numpy()
    probs = 1 / (1 + np.exp(-all_logits))

    try:
        macro_auc = roc_auc_score(all_targets, probs, average='macro')
    except ValueError:
        macro_auc = float('nan')  # can happen if a class has no positives in a small batch subset

    f1 = f1_score(all_targets, (probs >= 0.5).astype(int), average='macro', zero_division=0)
    return total_loss / len(loader.dataset), macro_auc, f1, probs, all_targets

RESUME_PATH = os.path.join(CACHE_DIR, 'resume_state_main.pt')

# ---- Lightweight resume support -----------------------------------------
# The SWA phase now needs ~34 epochs to run, so a full run is long enough
# that a Colab disconnect is a real risk. This saves a resumable snapshot
# every epoch; if interrupted, just re-run this cell and it continues
# from where it left off instead of losing all progress.
start_epoch = 0
history = {'train_loss': [], 'val_loss': [], 'val_auc': [], 'val_f1': []}
best_auc, patience_ctr, last_epoch_run = -1, 0, -1

if os.path.exists(RESUME_PATH):
    resume = torch.load(RESUME_PATH, map_location=DEVICE, weights_only=False)
    model.load_state_dict(resume['model_state'])
    optimizer.load_state_dict(resume['optimizer_state'])
    scheduler.load_state_dict(resume['scheduler_state'])
    scaler.load_state_dict(resume['scaler_state'])
    swa_model.load_state_dict(resume['swa_model_state'])
    start_epoch = resume['epoch'] + 1
    best_auc = resume['best_auc']
    patience_ctr = resume['patience_ctr']
    history = resume['history']
    print(f'Resuming from epoch {start_epoch} (best val macroAUC so far: {best_auc:.4f})')
else:
    print('No resume checkpoint found -- starting fresh.')
# ---------------------------------------------------------------------------

for epoch in range(start_epoch, EPOCHS):
    t0 = time.time()
    # CORRECTION: an earlier version of this notebook turned mixup off during the
    # SWA phase. In practice this removed the model's main regularizer and caused
    # severe overfitting (val_loss rose from 0.20 to 0.55+ over epochs 16->33 while
    # val_macroAUC steadily degraded from 0.9305 down to ~0.91). Keeping mixup ON
    # throughout -- including the SWA phase -- avoids this; SWA still helps by
    # averaging weights across a stable, well-regularized training trajectory.
    train_loss, _, _, _, _ = run_epoch(train_loader, train=True, mixup_alpha=MIXUP_ALPHA)
    val_loss, val_auc, val_f1, _, _ = run_epoch(val_loader, train=False)
    last_epoch_run = epoch

    if epoch >= SWA_START_EPOCH:
        swa_model.update_parameters(model)
        swa_scheduler.step()
    else:
        scheduler.step()

    history['train_loss'].append(train_loss)
    history['val_loss'].append(val_loss)
    history['val_auc'].append(val_auc)
    history['val_f1'].append(val_f1)

    print(f'Epoch {epoch+1:02d}/{EPOCHS} | train_loss {train_loss:.4f} | '
          f'val_loss {val_loss:.4f} | val_macroAUC {val_auc:.4f} | val_macroF1 {val_f1:.4f} | '
          f'{time.time()-t0:.1f}s')

    if val_auc > best_auc:
        best_auc = val_auc
        patience_ctr = 0
        torch.save({'model_state': model.state_dict(),
                    'classes': CLASSES,
                    'lead_mean': lead_mean, 'lead_std': lead_std}, CKPT_PATH)
        print(f'  -> new best model saved (val_macroAUC={val_auc:.4f})')
    else:
        patience_ctr += 1

    # save resume snapshot every epoch regardless of improvement
    torch.save({'model_state': model.state_dict(),
                'optimizer_state': optimizer.state_dict(),
                'scheduler_state': scheduler.state_dict(),
                'scaler_state': scaler.state_dict(),
                'swa_model_state': swa_model.state_dict(),
                'epoch': epoch, 'best_auc': best_auc,
                'patience_ctr': patience_ctr, 'history': history}, RESUME_PATH)

    # only allow early stopping *before* we enter the SWA phase -- once SWA starts
    # we want the fixed remaining epochs to run so the weight average is meaningful
    if patience_ctr >= EARLY_STOP_PATIENCE and epoch < SWA_START_EPOCH:
        print('Early stopping (pre-SWA phase).')
        break

# Recompute BatchNorm running statistics for the SWA-averaged weights (required by
# torch's SWA recipe), then save it as a separate checkpoint used for ensembling later.
if last_epoch_run >= SWA_START_EPOCH:
    torch.optim.swa_utils.update_bn(train_loader, swa_model, device=DEVICE)
    torch.save({'model_state': swa_model.module.state_dict(),
                'classes': CLASSES, 'lead_mean': lead_mean, 'lead_std': lead_std}, SWA_CKPT_PATH)
    print('SWA model BN stats refreshed and checkpoint saved.')
else:
    print('Training stopped before reaching SWA_START_EPOCH -- no SWA checkpoint produced.')

fig, axes = plt.subplots(1, 3, figsize=(16, 4))
axes[0].plot(history['train_loss'], label='train'); axes[0].plot(history['val_loss'], label='val')
axes[0].set_title('Loss'); axes[0].legend()
axes[1].plot(history['val_auc']); axes[1].set_title('Val Macro AUC')
axes[2].plot(history['val_f1']); axes[2].set_title('Val Macro F1')
plt.tight_layout(); plt.show()

"""## Change 4 — Checkpoint ensembling + test-time augmentation (TTA)
At inference we now average predictions from **(a)** the best-val-AUC checkpoint and **(b)** the SWA-averaged checkpoint, each evaluated with light TTA (clean signal + small time-shift + small amplitude scaling, averaged). Both are well-established, cheap ways to reduce prediction variance and typically add a small but real bump to AUC/F1 with **zero extra training cost** — they're inference-time only.
"""

from sklearn.metrics import (roc_auc_score, f1_score, accuracy_score,
                              classification_report, multilabel_confusion_matrix, roc_curve, auc as auc_fn)

def load_model_copy(path):
    m = MultiScaleCNNMambaAttnNet(in_channels=12, num_classes=N_CLASSES).to(DEVICE)
    ckpt = torch.load(path, map_location=DEVICE, weights_only=False)  # trusted, self-created checkpoint
    m.load_state_dict(ckpt['model_state'])
    m.eval()
    return m

models_for_ensemble = [load_model_copy(CKPT_PATH)]
if os.path.exists(SWA_CKPT_PATH):
    models_for_ensemble.append(load_model_copy(SWA_CKPT_PATH))
    print(f'Ensembling {len(models_for_ensemble)} checkpoints (best-val + SWA).')
else:
    print('SWA checkpoint not found -- evaluating the best-val checkpoint only.')

def tta_forward(m, xb):
    """Average logits over the clean signal + two light, physiologically
    plausible perturbations (small time shift, small amplitude scaling).
    This is inference-time-only and does not touch the true labels."""
    with torch.no_grad(), torch.amp.autocast('cuda', enabled=(DEVICE.type == 'cuda')):
        preds = [m(xb), m(torch.roll(xb, shifts=10, dims=-1)), m(xb * 1.05)]
    return torch.stack(preds, dim=0).mean(dim=0)

def get_probs(loader, use_tta=True):
    all_logits, all_targets = [], []
    with torch.no_grad():
        for xb, yb in loader:
            xb = xb.to(DEVICE)
            per_model_logits = []
            for m in models_for_ensemble:
                if use_tta:
                    per_model_logits.append(tta_forward(m, xb))
                else:
                    with torch.amp.autocast('cuda', enabled=(DEVICE.type == 'cuda')):
                        per_model_logits.append(m(xb))
            logits = torch.stack(per_model_logits, dim=0).mean(dim=0)
            all_logits.append(logits.float().cpu())
            all_targets.append(yb.float())
    logits = torch.cat(all_logits).numpy()
    targets = torch.cat(all_targets).numpy()
    probs = 1 / (1 + np.exp(-logits))
    return probs, targets

val_probs, val_targets = get_probs(val_loader)
test_probs, test_targets = get_probs(test_loader)

macro_auc = roc_auc_score(test_targets, test_probs, average='macro')
per_class_auc = roc_auc_score(test_targets, test_probs, average=None)
macro_f1_05 = f1_score(test_targets, (test_probs >= 0.5).astype(int), average='macro', zero_division=0)

print(f'TEST macro AUC: {macro_auc:.4f}')
print('\nPer-class AUC:')
for c, a in zip(CLASSES, per_class_auc):
    print(f'  {c:6s}: {a:.4f}')
print(f'\nMacro F1 (0.5 threshold): {macro_f1_05:.4f}')

print('\nClassification report (threshold=0.5):')
print(classification_report(test_targets, (test_probs >= 0.5).astype(int),
                             target_names=CLASSES, zero_division=0))

test_preds_05 = (test_probs >= 0.5).astype(int)

per_label_acc = [accuracy_score(test_targets[:, i], test_preds_05[:, i]) for i in range(N_CLASSES)]
mean_per_label_acc = np.mean(per_label_acc)
subset_acc = accuracy_score(test_targets, test_preds_05)

print("Per-class accuracy (0.5 threshold):")
for c, a in zip(CLASSES, per_label_acc):
    print(f"  {c:6s}: {a:.4f}")
print(f"\nOverall accuracy (mean per-label accuracy): {mean_per_label_acc:.4f}")



"""## Change 5 — Tune thresholds for F1, not accuracy
Your original code chose per-class thresholds by maximizing validation *accuracy*. On imbalanced multi-label classes this tends to push thresholds toward the majority prediction and can look good on accuracy while quietly hurting recall on the minority class. Optimizing for F1 instead aligns the threshold choice with the metric you're actually reporting.
"""

# NOTE: thresholds are now tuned to maximize per-class F1 on the val set,
# not accuracy. With imbalanced multi-label classes (e.g. HYP has far fewer
# positives), accuracy-optimal thresholds tend to just favor predicting the
# majority class -- F1-optimal thresholds better reflect the metric you
# actually care about and report in the paper.
thresholds = np.zeros(N_CLASSES)
candidate_ths = np.arange(0.05, 0.96, 0.01)

for i, c in enumerate(CLASSES):
    best_th, best_f1 = 0.5, -1
    for th in candidate_ths:
        f1_i = f1_score(val_targets[:, i], (val_probs[:, i] >= th).astype(int), zero_division=0)
        if f1_i > best_f1:
            best_f1, best_th = f1_i, th
    thresholds[i] = best_th
    print(f'{c:6s}: tuned threshold (max F1) = {best_th:.2f}  (val F1 {best_f1:.4f})')

test_preds_tuned = (test_probs >= thresholds[None, :]).astype(int)
per_label_acc_tuned = [accuracy_score(test_targets[:, i], test_preds_tuned[:, i]) for i in range(N_CLASSES)]
mean_acc_tuned = np.mean(per_label_acc_tuned)
subset_acc_tuned = accuracy_score(test_targets, test_preds_tuned)
f1_tuned = f1_score(test_targets, test_preds_tuned, average='macro', zero_division=0)

print('\nPer-class test accuracy (F1-tuned thresholds):')
for c, a in zip(CLASSES, per_label_acc_tuned):
    print(f'  {c:6s}: {a:.4f}')
print(f'\nMean per-label accuracy (F1-tuned thresholds): {mean_acc_tuned:.4f}')
print(f'Subset (exact-match) accuracy (F1-tuned):        {subset_acc_tuned:.4f}')
print(f'Macro F1 (F1-tuned thresholds):                  {f1_tuned:.4f}')
print(f'Macro AUC (threshold-independent):                {macro_auc:.4f}')

fig, ax = plt.subplots(figsize=(6, 6))
for i, c in enumerate(CLASSES):
    fpr, tpr, _ = roc_curve(test_targets[:, i], test_probs[:, i])
    ax.plot(fpr, tpr, label=f'{c} (AUC={auc_fn(fpr, tpr):.3f})')
ax.plot([0, 1], [0, 1], 'k--', alpha=0.3)
ax.set_xlabel('False Positive Rate'); ax.set_ylabel('True Positive Rate')
ax.set_title('Per-class ROC — Test set'); ax.legend(loc='lower right')
plt.tight_layout(); plt.show()

cms = multilabel_confusion_matrix(test_targets, test_preds_tuned)
fig, axes = plt.subplots(1, 5, figsize=(20, 4))
for i, (c, cm) in enumerate(zip(CLASSES, cms)):
    axes[i].imshow(cm, cmap='Blues')
    axes[i].set_title(c)
    for r in range(2):
        for col in range(2):
            axes[i].text(col, r, cm[r, col], ha='center', va='center')
    axes[i].set_xticks([0, 1]); axes[i].set_yticks([0, 1])
    axes[i].set_xticklabels(['Pred 0', 'Pred 1']); axes[i].set_yticklabels(['True 0', 'True 1'])
plt.tight_layout(); plt.show()

"""## Change 6 — Save F1-tuned thresholds into the deployment checkpoint

Run this **last**, after the "Change 5" threshold-tuning cell above (it needs
`val_probs`, `val_targets`, `CLASSES`, and `N_CLASSES` already in memory from
the checkpoint-ensembling/evaluation cell, and it needs `CKPT_PATH` to already
exist on disk from the training cell).

This re-opens the saved `best_mscma_net_main.pt` checkpoint and adds a
`'thresholds'` key to it, so anything that loads the checkpoint later (e.g. a
deployment backend) can read the tuned per-class thresholds straight from the
file instead of recomputing them from the validation set every time.

"""

import os
import numpy as np
import torch
from sklearn.metrics import f1_score

# Reuses CKPT_PATH from the training cell above (best_mscma_net_main.pt) so
# there's no risk of pointing this at the wrong file.
DEPLOY_CKPT_PATH = CKPT_PATH

# NOTE: `thresholds` was already computed in the "Change 5" cell above from
# val_probs/val_targets. Recomputed here as `tuned_thresholds` only so this
# cell is self-contained if you want to run it on its own later.
tuned_thresholds = np.zeros(N_CLASSES, dtype=np.float32)
for i in range(N_CLASSES):
    best_th, best_f1 = 0.5, -1
    for th in np.arange(0.05, 0.96, 0.01):
        f1 = f1_score(val_targets[:, i], (val_probs[:, i] >= th).astype(int), zero_division=0)
        if f1 > best_f1:
            best_f1, best_th = f1, th
    tuned_thresholds[i] = best_th

ckpt = torch.load(DEPLOY_CKPT_PATH, map_location='cpu', weights_only=False)
ckpt['thresholds'] = tuned_thresholds
torch.save(ckpt, DEPLOY_CKPT_PATH)
print("Saved thresholds:", dict(zip(CLASSES, tuned_thresholds)))
print("Checkpoint now contains keys:", list(ckpt.keys()))

ckpt_check = torch.load(DEPLOY_CKPT_PATH, map_location='cpu', weights_only=False)
print(ckpt_check.keys())
print(ckpt_check['thresholds'])

import os
import numpy as np
import torch
import wfdb

# ---- EDIT if your checkpoint path / variable names differ ----
CKPT_PATH = os.path.join(CACHE_DIR, 'best_mscma_net_main.pt')   # or your deployed checkpoint's path
CONFIDENCE_THRESHOLD = 0.65
OUT_DIR = '/content/demo_csvs_verified'
# ----------------------------------------------------------------

LEAD_ORDER = ["I", "II", "III", "aVR", "aVL", "aVF", "V1", "V2", "V3", "V4", "V5", "V6"]
os.makedirs(OUT_DIR, exist_ok=True)

# Load the exact checkpoint you deploy, so "correct here" == "correct in the app".
ckpt = torch.load(CKPT_PATH, map_location=DEVICE, weights_only=False)
model.load_state_dict(ckpt['model_state'])
model.eval()

test_df = Y[Y.strat_fold == 10].copy()
test_df['n_labels'] = test_df.diagnostic_superclass.apply(len)
clean_single_label = test_df[test_df.n_labels == 1].copy()
clean_single_label['label'] = clean_single_label.diagnostic_superclass.apply(lambda l: l[0])


def predict_one(raw_t_leads: np.ndarray) -> np.ndarray:
    x = (raw_t_leads - lead_mean) / (lead_std + 1e-8)
    x_t = torch.from_numpy(x.T[None]).float().to(DEVICE)   # (1, 12, 1000)
    with torch.no_grad():
        probs = torch.sigmoid(model(x_t)).cpu().numpy()[0]
    return probs


verified = {}
checked_counts = {c: 0 for c in CLASSES}

for cls in CLASSES:
    candidates = clean_single_label[clean_single_label.label == cls]
    for _, row in candidates.iterrows():
        checked_counts[cls] += 1
        sig, _ = wfdb.rdsamp(PTBXL_ROOT + row.filename_lr)
        probs = predict_one(sig.astype(np.float32))
        pred_idx = int(np.argmax(probs))
        pred_cls = CLASSES[pred_idx]
        if pred_cls == cls and probs[pred_idx] >= CONFIDENCE_THRESHOLD:
            verified[cls] = (row, probs)
            break

print('Search summary:')
for cls in CLASSES:
    status = 'FOUND' if cls in verified else 'NOT FOUND'
    print(f'  {cls:6s}: checked {checked_counts[cls]:4d} candidates -> {status}')

print()
for cls, (row, probs) in verified.items():
    sig, _ = wfdb.rdsamp(PTBXL_ROOT + row.filename_lr)
    fname = os.path.join(OUT_DIR, f'verified_{cls}_ecgid{row.name}.csv')
    header = ','.join(LEAD_ORDER)
    np.savetxt(fname, sig, delimiter=',', header=header, comments='', fmt='%.5f')
    print(f'{cls}: saved {fname}  |  model confidence on {cls} = {probs[CLASSES.index(cls)]:.3f}  '
          f'|  full probs = {dict(zip(CLASSES, probs.round(3)))}')

missing = set(CLASSES) - set(verified.keys())
if missing:
    print(f'\nCould not find a confidently-correct example for: {missing}')
    print('Try lowering CONFIDENCE_THRESHOLD (e.g. to 0.55), or note this as a')
    print('known weak class for your model — worth mentioning proactively to your mentor.')

print(f'\nZip and download with:')
print(f"  !zip -r demo_csvs_verified.zip {OUT_DIR}")

!zip -r demo_csvs_verified.zip /content/demo_csvs_verified

from google.colab import files
files.download('demo_csvs_verified.zip')

from sklearn.metrics import multilabel_confusion_matrix
import numpy as np

cms = multilabel_confusion_matrix(test_targets, test_preds_tuned)
print(f"{'Class':6s} {'Sens':>7s} {'Spec':>7s} {'Prec':>7s} {'F1':>7s} {'MCC':>7s} {'Acc':>7s}")
for i, c in enumerate(CLASSES):
    tn, fp, fn, tp = cms[i].ravel()
    sens = tp / (tp + fn + 1e-9)
    spec = tn / (tn + fp + 1e-9)
    prec = tp / (tp + fp + 1e-9)
    f1   = 2*tp / (2*tp + fp + fn + 1e-9)
    mcc  = (tp*tn - fp*fn) / (np.sqrt((tp+fp)*(tp+fn)*(tn+fp)*(tn+fn)) + 1e-9)
    acc  = (tp+tn) / (tp+tn+fp+fn)
    print(f"{c:6s} {sens:7.4f} {spec:7.4f} {prec:7.4f} {f1:7.4f} {mcc:7.4f} {acc:7.4f}")

from sklearn.metrics import confusion_matrix
import numpy as np
import matplotlib.pyplot as plt

# Restrict to test-set records with exactly one true class (clean, unambiguous ground truth)
single_label_mask = test_targets.sum(axis=1) == 1
y_true_single = np.argmax(test_targets[single_label_mask], axis=1)
y_pred_single = np.argmax(test_probs[single_label_mask], axis=1)

print(f"Single-label test records used: {single_label_mask.sum()} / {len(test_targets)}")

cm = confusion_matrix(y_true_single, y_pred_single, labels=range(N_CLASSES))

fig, ax = plt.subplots(figsize=(6, 6))
im = ax.imshow(cm, cmap='Blues')
ax.set_xticks(range(N_CLASSES)); ax.set_yticks(range(N_CLASSES))
ax.set_xticklabels(CLASSES); ax.set_yticklabels(CLASSES)
ax.set_xlabel('Predicted'); ax.set_ylabel('True')
ax.set_title('Confusion Matrix — MSCMA-Net (Test set, single-label subset)')

for i in range(N_CLASSES):
    for j in range(N_CLASSES):
        ax.text(j, i, cm[i, j], ha='center', va='center',
                 color='white' if cm[i, j] > cm.max()/2 else 'black')

plt.colorbar(im, ax=ax, fraction=0.046)
plt.tight_layout()
plt.savefig('confusion_matrix_single.png', dpi=200)
plt.show()

# ============================================================
# REPLACES CELL 17 (training curves: loss / val AUC / val F1)
# ============================================================
import matplotlib.pyplot as plt

c_teal, c_purple, c_brick = "#0E7C6B", "#4B4FA6", "#9C4A2E"

fig, axes = plt.subplots(1, 3, figsize=(12, 3.4))
for ax in axes:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.grid(color="#E5E5E5", linewidth=0.8, zorder=0)

axes[0].plot(history['train_loss'], label='train', color=c_teal, linewidth=1.6, zorder=3)
axes[0].plot(history['val_loss'], label='val', color=c_brick, linewidth=1.6, zorder=3)
axes[0].set_title('Loss', fontsize=10.5, fontweight='bold')
axes[0].set_xlabel('Epoch', fontsize=9); axes[0].legend(fontsize=8.5, frameon=False)

axes[1].plot(history['val_auc'], color=c_purple, linewidth=1.6, zorder=3)
axes[1].set_title('Validation Macro AUC', fontsize=10.5, fontweight='bold')
axes[1].set_xlabel('Epoch', fontsize=9)

axes[2].plot(history['val_f1'], color=c_teal, linewidth=1.6, zorder=3)
axes[2].set_title('Validation Macro F1', fontsize=10.5, fontweight='bold')
axes[2].set_xlabel('Epoch', fontsize=9)

for ax in axes:
    ax.tick_params(labelsize=8.5)

plt.tight_layout()
plt.savefig('training_curves.pdf', bbox_inches='tight')
plt.savefig('training_curves.png', dpi=300, bbox_inches='tight')
plt.show()


# ============================================================
# REPLACES CELL 24 (ROC curves, 5 classes)
# ============================================================
from sklearn.metrics import roc_curve, auc as auc_fn

palette = ["#0E7C6B", "#9C4A2E", "#4B4FA6", "#5A6472", "#B08A2E"]

fig, ax = plt.subplots(figsize=(5.5, 5.5))
for i, c in enumerate(CLASSES):
    fpr, tpr, _ = roc_curve(test_targets[:, i], test_probs[:, i])
    ax.plot(fpr, tpr, label=f'{c} (AUC={auc_fn(fpr, tpr):.3f})',
            color=palette[i], linewidth=1.6)
ax.plot([0, 1], [0, 1], '--', color="#AAAAAA", linewidth=1, alpha=0.8)
ax.set_xlabel('False Positive Rate', fontsize=9.5)
ax.set_ylabel('True Positive Rate', fontsize=9.5)
ax.set_title('ROC curves — MSCMA-Net test set', fontsize=10.5, fontweight='bold')
ax.legend(fontsize=8.5, loc='lower right', frameon=False)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.grid(color="#E5E5E5", linewidth=0.8, zorder=0)
ax.tick_params(labelsize=8.5)

plt.tight_layout()
plt.savefig('roc_curves.pdf', bbox_inches='tight')
plt.savefig('roc_curves.png', dpi=300, bbox_inches='tight')
plt.show()


# ============================================================
# REPLACES CELL 32 (confusion matrix, single-label subset)
# ============================================================
from sklearn.metrics import confusion_matrix
import matplotlib as mpl

cm = confusion_matrix(y_true_single, y_pred_single, labels=range(N_CLASSES))

fig, ax = plt.subplots(figsize=(5.2, 5.2))
cmap = mpl.colors.LinearSegmentedColormap.from_list("teal_light", ["#FFFFFF", "#0E7C6B"])
im = ax.imshow(cm, cmap=cmap)
ax.set_xticks(range(N_CLASSES)); ax.set_yticks(range(N_CLASSES))
ax.set_xticklabels(CLASSES, fontsize=9.5); ax.set_yticklabels(CLASSES, fontsize=9.5)
ax.set_xlabel('Predicted', fontsize=9.5); ax.set_ylabel('True', fontsize=9.5)
ax.set_title('Confusion matrix — MSCMA-Net\n(test set, single-label subset)',
             fontsize=10.5, fontweight='bold')

for i in range(N_CLASSES):
    for j in range(N_CLASSES):
        ax.text(j, i, cm[i, j], ha='center', va='center', fontsize=9.5,
                 color='white' if cm[i, j] > cm.max() * 0.55 else '#1A1A1A')

for spine in ax.spines.values():
    spine.set_visible(False)
plt.colorbar(im, ax=ax, fraction=0.046)
plt.tight_layout()
plt.savefig('confusion_matrix.pdf', bbox_inches='tight')
plt.savefig('confusion_matrix.png', dpi=300, bbox_inches='tight')
plt.show()

# ============================================================
# FIXED ROC snippet — uses the SAME class colors as class_distribution.png
# Paste into your Colab notebook, replacing the previous ROC cell.
# ============================================================
from sklearn.metrics import roc_curve, auc as auc_fn
import matplotlib.pyplot as plt

# Same mapping as class_distribution.png — keep this fixed across ALL figures
CLASS_COLORS = {
    "NORM": "#5A6472",
    "MI":   "#0E7C6B",
    "STTC": "#4B4FA6",
    "CD":   "#9C4A2E",
    "HYP":  "#B08A2E",
}
LINESTYLES = {"NORM": "-", "MI": "-", "STTC": "--", "CD": "-.", "HYP": ":"}  # grayscale-safe backup

fig, ax = plt.subplots(figsize=(5.5, 5.5))
for c in CLASSES:
    i = CLASSES.index(c)
    fpr, tpr, _ = roc_curve(test_targets[:, i], test_probs[:, i])
    ax.plot(fpr, tpr, label=f'{c} (AUC={auc_fn(fpr, tpr):.3f})',
            color=CLASS_COLORS[c], linestyle=LINESTYLES[c], linewidth=1.7)
ax.plot([0, 1], [0, 1], '--', color="#AAAAAA", linewidth=1, alpha=0.8)
ax.set_xlabel('False Positive Rate', fontsize=9.5)
ax.set_ylabel('True Positive Rate', fontsize=9.5)
ax.set_title('ROC curves — MSCMA-Net test set', fontsize=10.5, fontweight='bold')
ax.legend(fontsize=8.5, loc='lower right', frameon=False)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.grid(color="#E5E5E5", linewidth=0.8, zorder=0)
ax.tick_params(labelsize=8.5)

plt.tight_layout()
plt.savefig('roc_curves.pdf', bbox_inches='tight')
plt.savefig('roc_curves.png', dpi=300, bbox_inches='tight')
plt.show()

import numpy as np

CLASSES = ['NORM', 'MI', 'STTC', 'CD', 'HYP']
samples = {}

for i, c in enumerate(CLASSES):
    # find a test record whose ONLY true label is this class (clean example)
    mask = (test_targets.sum(axis=1) == 1) & (test_targets[:, i] == 1)
    idx = np.where(mask)[0]
    if len(idx) == 0:
        print(f"No clean single-label example for {c}, skipping")
        continue
    j = idx[0]                       # first matching record
    samples[c] = X_test[j]           # shape should be (12, 1000) or (1000, 12)

# save everything into one npz file
np.savez('ecg_examples.npz', **samples, sampling_rate=SAMPLING_RATE, classes=CLASSES)
print(samples.keys())

from google.colab import files
files.download('ecg_examples.npz')

print(samples['NORM'].shape)

# =========================================================================
# Real self-attention visualization for MSCMA-Net
# -------------------------------------------------------------------------
# Paste as a NEW CELL in main_model_mscma_net_final.ipynb, AFTER the cell
# that loads `model` with trained weights and computes test_probs/test_targets
# (same place you added the Grad-CAM cell -- this can replace it).
#
# Why this instead of Grad-CAM: your model already computes real attention
# weights in `AttentionBlock.mha`. Grad-CAM at stage3 only shows what the
# CNN extracted BEFORE the Mamba blocks and attention layer do their work --
# this pulls the actual weights the classifier's final feature vector was
# built from, no approximation needed.
# =========================================================================

import types
import numpy as np
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

# ---- 1. Monkey-patch AttentionBlock.forward to also return its weights ----
# (the model's own forward() calls need_weights=False for speed during
#  normal training/inference -- we only turn it on for this diagnostic pass)
_captured = {}

def _attn_forward_capture(self, x):
    h = self.norm1(x)
    attn_out, attn_w = self.mha(h, h, h, need_weights=True, average_attn_weights=False)
    # attn_w: (B, num_heads, L, L) -- query x key attention per head
    _captured['weights'] = attn_w.detach()
    x = x + attn_out
    x = x + self.ff(self.norm2(x))
    return x

_original_attn_forward = model.attn.forward   # save so we can restore it afterward
model.attn.forward = types.MethodType(_attn_forward_capture, model.attn)

# ---- 2. Rebuild the same single-label, correctly-classified example set ----
single_label_mask = test_targets.sum(axis=1) == 1
y_true_single = np.argmax(test_targets[single_label_mask], axis=1)
y_pred_single = np.argmax(test_probs[single_label_mask], axis=1)
conf_single = test_probs[single_label_mask].max(axis=1)

all_test_x = []
for xb, _ in test_loader:
    all_test_x.append(xb)
X_test_tensor = torch.cat(all_test_x, dim=0)

T_RAW = X_test_tensor.shape[-1]      # 1000
T_ATTN = T_RAW // 8                  # 125, after 3x maxpool(2)

fig, axes = plt.subplots(len(CLASSES), 1, figsize=(11, 2.2 * len(CLASSES)), sharex=True)

for i, cls in enumerate(CLASSES):
    idxs = np.where((y_true_single == i) & (y_pred_single == i))[0]
    if len(idxs) == 0:
        axes[i].set_title(f"{cls}: no correctly-classified single-label example found")
        continue
    best_idx = idxs[np.argmax(conf_single[idxs])]

    x = X_test_tensor[single_label_mask][best_idx:best_idx + 1].to(DEVICE)

    model.eval()
    with torch.no_grad():
        _ = model(x)   # triggers the patched forward, fills _captured['weights']

    attn_w = _captured['weights'][0]                 # (num_heads, L, L)
    attn_w = attn_w.mean(dim=0)                       # average over heads -> (L, L)
    received = attn_w.mean(dim=0)                     # avg attention each position RECEIVES -> (L,)
    received = received.cpu().numpy()
    received = (received - received.min()) / (received.max() - received.min() + 1e-8)

    # upsample from T_ATTN (125) back to T_RAW (1000) -- matches the 3x maxpool(2) downsampling
    received_t = torch.tensor(received)[None, None, :]
    received_up = F.interpolate(received_t, size=T_RAW, mode='linear', align_corners=False)
    heatmap = received_up.squeeze().numpy()

    lead_ii = x[0, 1].detach().cpu().numpy()

    ax = axes[i]
    ax.plot(lead_ii, color='black', linewidth=0.9)
    ax.imshow(heatmap[np.newaxis, :], cmap='Reds', aspect='auto', alpha=0.45,
              extent=[0, len(lead_ii), lead_ii.min(), lead_ii.max()])
    ax.set_ylabel(cls, fontsize=11, fontweight='bold', rotation=0, ha='right', va='center')
    ax.set_yticks([])

axes[-1].set_xlabel("Timestep (10 s @ 100 Hz, lead II shown)")
fig.suptitle("Self-attention: which timesteps MSCMA-Net's attention layer weights most",
              fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig("attention_examples.png", dpi=200, bbox_inches="tight")
plt.show()

# restore the original forward so normal training/inference is unaffected afterward
model.attn.forward = _original_attn_forward
print("Saved attention_examples.png -- upload back to Claude to check.")
print("model.attn.forward restored to original -- safe to keep using `model` as normal.")