import os
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

SECRET_KEY = os.getenv("SECRET_KEY", "dev-secret-change-me")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", "480"))

DATABASE_URL = os.getenv("DATABASE_URL", f"sqlite:///{BASE_DIR}/database/patients.db")

MODEL_CHECKPOINT = os.path.join(BASE_DIR, os.getenv("MODEL_CHECKPOINT", "weights/best_model.pth"))
MODEL_CHECKPOINT_ALT = os.path.join(BASE_DIR, os.getenv("MODEL_CHECKPOINT_ALT", "weights/best_model_swa.pth"))

N_LEADS = int(os.getenv("N_LEADS", "12"))
SEQ_LEN = int(os.getenv("SEQ_LEN", "1000"))
CLASSES = os.getenv("CLASSES", "NORM,MI,STTC,CD,HYP").split(",")

UPLOAD_DIR = os.path.join(BASE_DIR, "uploads")
REPORTS_DIR = os.path.join(BASE_DIR, "reports_out")

os.makedirs(os.path.join(BASE_DIR, "database"), exist_ok=True)
os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs(REPORTS_DIR, exist_ok=True)

# Clinical framing only — not a diagnosis. Shown on every prediction/report.
CLINICAL_DISCLAIMER = (
    "This output is generated by an AI decision-support tool (MSCMA-Net) and is "
    "intended to assist, not replace, clinical judgment. All findings must be "
    "reviewed and confirmed by a qualified clinician before any care decision."
)

# Simple risk-level rule: highest priority abnormal class present drives the banner.
RISK_ORDER = ["MI", "CD", "STTC", "HYP", "NORM"]
HIGH_RISK_CLASSES = {"MI", "CD"}
